---
driver:
  name: docker
  hostname: helm.ci.local
  #socket: tcp://127.0.0.1:2376
  use_sudo: false



provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  formula: helm
  log_level: info
  state_top:
    base:
      "*":
        - helm
  pillars:
    top.sls:
      base:
        "*":
          - helm
  grains:
    noservices: True

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

verifier:
  name: inspec
  sudo: true


suites:
  - name: single
    provisioner:
      pillars-from-files:
        helm.sls: tests/pillar/single.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
