# Sample check
check:
  local_helm_proc:
    command: "PATH=$PATH:/usr/lib64/nagios/plugins:/usr/lib/nagios/plugins check_procs -C helm -u helm -c 1:1"
    interval: 60
    occurrences: 1
    subscribers:
    - local-helm-client
